### ISSUE TITLE
H2 name is already taken as a well known Java database.

### ISSUE THREAD

**Issue by kpatrick** [carllerche/h2#168]

**Comment by carllerche** [comment]
Thanks for the report. After considering the potential confusion between a java based database and a Rust library implementing the HTTP/2.0 protocol, I am opting to keep the current name.

The deciding factor is that the HTTP/2.0 specification has officially registered the `h2` string to identify the protocol. As such, I would recommend filing this issue against the HTTP/2.0 specification in order to make them aware of the naming conflict.
