### ISSUE TITLE
API polish

### ISSUE THREAD

**Issue by carllerche** [carllerche/h2#75]
* `Client::request` should be renamed `Client::send_request`
* `send_trailers` and `send_reset` should take `self`
* `Client` is missing `send_reset`
* Dropping the read body should reset the stream.

**Comment by hawkw** [comment]
@carllerche w.r.t the "`send_trailers` and `send_reset` should take `self`" point, is this the `send_{trailers, reset}` method on `StreamRef`, `Streams`, `proto::Send`, `server::Stream`, or all of the above?

**Comment by seanmonstar** [comment]
A possiblity is for the `Stream` to implement `Sink`, and so all actions of sending new frames are down on the `Stream`, instead of the `Client`. That'd mean you don't need to remember the stream ID, and wouldn't need to keep both types in scope, as all sending could be done on the `Stream`. And then `shutdown` could send a reset.

**Comment by carllerche** [comment]
So, I think that we determined that `send_trailers` and `send_reset` cannot take `self` because you can send those frames and then use `self` to receive the response.

**Comment by carllerche** [comment]
I'm also going to break this issue up into individual issues for better tracking.

**Comment by carllerche** [comment]
Ok, I've split this issue out to individual items. I'm going to close this issue now.
